name = "LoggingExtras"
uuid = "bda5643c-bbc4-11e8-2bd7-9ffae705afc0"
authors = ["Lyndon White <oxinabox@ucc.asn.au>"]
version = "0.3.0"

[compat]
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
